openapi: 3.0.3
info:
  title: Docker Desktop tools API
  version: 0.0.0
  x-redocly-package-name: tools
servers:
- url: /
tags:
- name: tools
paths:
  /apps:
    get:
      operationId: listOAuthApps
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OAuthApp'
                type: array
          description: success
        "500":
          description: unexpected error
      summary: Lists all app objects.
      tags:
      - tools
  /apps/{app}:
    delete:
      operationId: deleteOAuthApp
      parameters:
      - explode: false
        in: path
        name: app
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: success
        "500":
          description: unexpected error
      summary: Unauthorizes an app.
      tags:
      - tools
    get:
      operationId: getOAuthApp
      parameters:
      - explode: false
        in: path
        name: app
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthApp'
          description: success
        "500":
          description: unexpected error
      summary: Returns an app object.
      tags:
      - tools
    post:
      operationId: postOAuthApp
      parameters:
      - explode: false
        in: path
        name: app
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: scopes
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: unexpected error
      summary: Authorize an app.
      tags:
      - tools
  /apps/{app}/tools/{tool}:
    delete:
      operationId: deleteOAuthAppTool
      parameters:
      - explode: false
        in: path
        name: app
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: tool
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: success
        "500":
          description: unexpected error
      summary: Remove a tool from an app.
      tags:
      - tools
    post:
      operationId: postOAuthAppTool
      parameters:
      - explode: false
        in: path
        name: app
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: tool
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: success
        "500":
          description: unexpected error
      summary: Add a tool to an app.
      tags:
      - tools
components:
  schemas:
    OAuthScopes:
      example:
        metadata:
        - metadata
        - metadata
        name: name
        description: description
      properties:
        name:
          type: string
        description:
          type: string
        metadata:
          items:
            type: string
          type: array
      type: object
    OAuthApp:
      example:
        app: app
        provider: provider
        authorized: true
        scopes:
        - metadata:
          - metadata
          - metadata
          name: name
          description: description
        - metadata:
          - metadata
          - metadata
          name: name
          description: description
        tools:
        - tools
        - tools
      properties:
        app:
          type: string
        tools:
          items:
            type: string
          type: array
        authorized:
          type: boolean
        provider:
          type: string
        scopes:
          items:
            $ref: '#/components/schemas/OAuthScopes'
          type: array
      required:
      - app
      - authorized
      - provider
      - tools
      type: object
    AuthResponse:
      example:
        browserUrl: browserUrl
        authType: authType
      properties:
        browserUrl:
          type: string
        authType:
          type: string
      type: object
