openapi: 3.0.3
info:
  version: 0.0.0
  title: Docker Desktop tools API
  x-redocly-package-name: tools
tags:
  - name: tools
paths:
  /apps:
    get:
      summary: Lists all app objects.
      tags: [ tools ]
      operationId: listOAuthApps
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OAuthApp'
        '500':
          description: unexpected error
  /apps/{app}:
    post:
      summary: Authorize an app.
      tags: [ tools ]
      operationId: postOAuthApp
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
        - name: scopes
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
    get:
      summary: Returns an app object.
      tags: [ tools ]
      operationId: getOAuthApp
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthApp'
        '500':
          description: unexpected error
    delete:
      summary: Unauthorizes an app.
      tags: [ tools ]
      operationId: deleteOAuthApp
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
        '500':
          description: unexpected error
  /apps/{app}/tools/{tool}:
    post:
      summary: Add a tool to an app.
      tags: [ tools ]
      operationId: postOAuthAppTool
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
        - name: tool
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
        '500':
          description: unexpected error
    delete:
        summary: Remove a tool from an app.
        tags: [ tools ]
        operationId: deleteOAuthAppTool
        parameters:
          - name: app
            in: path
            required: true
            schema:
              type: string
          - name: tool
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: success
          '500':
            description: unexpected error
components:
  schemas:
    OAuthScopes:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        metadata:
          type: array
          items:
            type: string
    OAuthApp:
      type: object
      properties:
        app:
          type: string
        tools:
          type: array
          items:
            type: string
        authorized:
          type: boolean
        provider:
          type: string
        scopes:
          type: array
          items:
            $ref: '#/components/schemas/OAuthScopes'
      required:
        - app
        - tools
        - authorized
        - provider
    AuthResponse:
      type: object
      properties:
        browserUrl:
          type: string
        authType:
          type: string
